### ISSUE TITLE
Caffe Models and Prototxt

### ISSUE THREAD

**Issue by cagdasbak** [imatge-upc/saliency-2016-cvpr#3]
Are you planning to share your caffe model and also prototxt for training. (Also can you explain how can you feed groundtruths to network for training ? )

**Comment by kevinmcguinness** [comment]
Attached is a sample train_val.prototxt. The ground truth is simply loaded using another data layer and a separate leveldb.

[train_val.prototxt.txt](https://github.com/imatge-upc/saliency-2016-cvpr/files/167479/train_val.prototxt.txt)

**Comment by xavigiro** [comment]
HI @cagdasbak ,

did we solve your question ? If so, could you please close the issue ?

Thanks.

**Comment by cagdasbak** [comment]
Thanks for your response. Just also i have couple of question about usage. Are these leveldb files both generated for 3channel images. (Did you convert saliency images into rgb format before generate leveldb for saliency. ). Also at your paper you said, you normalized images(both input and corresponding saliencies )between [-1 1].). Did you do this operation before generate leveldb file ? If it is possible it would be gread if you alse share your script for generating leveldb files. 
Thanks

**Comment by kevinmcguinness** [comment]
The leveldb files for the input images are in the usual 3 channel BGR format. The leveldb files for the saliency maps only have 1 channel. Saliency values are stored unnormalized as values that range from 0 to 255 (so they can be stored in bytes rather than floats, which makes a big difference in encoding/decoding speed). The `train_val.prototxt` I attached the last time does the mean subtraction and zero centering in the data layers at train time.

We coded our own leveldb generator rather than using the caffe command line tools. Unfortunately the code for this isn't a standalone script but part of a larger codebase, which makes it a little difficult to extract for sharing. It should be fairly straightforward to code a new one using one of the Python leveldb bindings like [plyvel](https://plyvel.readthedocs.org/en/latest/) and  the function `caffe.io.array_to_datum`
