### ISSUE TITLE
A Problem with the Deep Model

### ISSUE THREAD

**Issue by kfxw** [imatge-upc/saliency-2016-cvpr#6]
Hi, I'm now using the deep model with Caffe. However, when I tried to load the net an error always occurs:
**Check failed: target_blobs[j]->num() == source_layer.blobs(j).num() (96 vs. 0)**
I suspect that the deploy file and the model are not correspond, are they?
The deploy file is on this github project and my code is here:

``` python
import caffe
import glob
import os
import numpy as np
from scipy import misc

inputFolder = r'../../image'
outputFolder = r'./results'
modelFile = 'deep_net_model.caffemodel'
deployFile = 'deep_net_deploy.prototxt'

if os.path.isdir(outputFolder) == False:
    os.mkdir(outputFolder)

net = caffe.Net(deployFile, modelFile, caffe.TEST)
```

It stops at caffe.Net().

**Comment by kevinmcguinness** [comment]
I checked the model and prototxt on my machine and they work fine. It appears that this issue is related to compatibility of the model with the version of caffe that you are using (compatibility problems are known to produce similar error messages, see: https://github.com/BVLC/caffe/issues/2158). Can you try using the model with a newer version of caffe and see if the problem persists?

**Comment by kfxw** [comment]
Great, that is. Caffe-rc2 seems to be really old. The present master version dose work. Thanks!
